# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
     brasserie.jwt_authenticated_listener.class: BrasserieBundle\EventListener\AuthenticationSuccessListener

services:
    fos_user.doctrine_registry:
        alias: doctrine
          
    password_or_facebook_authenticator:
        class:     BrasserieBundle\Service\PasswordOrFacebookAuthenticator
        arguments: ["@security.password_encoder", "@request_stack", "@service_container", "@logger"]
        tags:
            - { name: monolog.logger, channel: service }
            
    brasserie_api.event.jwt_authenticated_listener:
        class: %brasserie.jwt_authenticated_listener.class%
        arguments: 
            - @serializer
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }