<?php

namespace BrasserieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BrassinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrassinRepository extends EntityRepository
{

    /**
     * Get routes for historic.
     *
     * @return array
     */
    public function getHistoric($user)
    {
        $qb = $this->createQueryBuilder('r')
            ->where('r.owner = :user')
            ->andWhere('r.origin IS NOT NULL')
            ->andWhere('r.arrival IS NOT NULL')
            ->andWhere('r.originAddress IS NOT NULL')
            ->andWhere('r.arrivalAddress IS NOT NULL')
            ->orderBy('r.createdAt', 'DESC')
            ->setParameter('user', $user);

        return $qb->getQuery()->getResult();
    }

}
