<?php

namespace BrasserieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmbouteillageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmbouteillageRepository extends EntityRepository
{
}
